version: 2
jobs:
  build:
    
    working_directory: ~/spring-boot-app

    docker:
      - image: circleci/openjdk:8-jdk-stretch\

    steps:

      - checkout

      - restore_cache:
          key: spring-boot-app-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: spring-boot-app-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
  
      - store_artifacts:
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar
